python ./finetune_BERT.py --data-dir './data/finetune/'    \
    --bert-model bert-base-uncased  \
    --task-name els   \
    --output-dir './checkpoints/finetune-BERT/'  \
    --cache-dir './models/bert-base-uncased' \
    --use-proportion 0.3   \
    --num-train-epochs 3   \
    --max-seq-length 512    \
    --do-train  \
    --train-batch-size 32  \
    --learning-rate 2e-5    \
    --weight-decay 0.01 \
    --save-all  \
    --show-eval-detail